#!/usr/bin/env bash
# Mirror the current command queue into Collie's launcher rows, so the queue is usable from a
# phone.
#
# Collie has no terminal emulator and sends no mouse events (ARCHITECTURE.md §4-§6), so the
# panel's click targets cannot work there. Its launcher rows can: each is a button that opens a
# fresh shell and runs its command. We point every row at scripts/review-run.sh, which prints the
# real command and asks before running it - launchers.toml accepts no confirm option of its own,
# and this file is the allowlist POST /api/launch matches against, so the rows must stay bounded.
#
# Only the managed block is rewritten. Rows written by hand outside the markers are preserved.
set -uo pipefail

LOG="${REVIEW_PANEL_LOG:-$HOME/.claude/review.log}"
DONE_LOG="${REVIEW_PANEL_DONE_LOG:-$HOME/.claude/review-done.log}"
CLEARED_LOG="${REVIEW_PANEL_CLEARED_LOG:-$HOME/.claude/review-cleared.log}"
MAX_ROWS="${REVIEW_PANEL_COLLIE_ROWS:-12}"
BEGIN='# >>> herdr-review-panel: generated, edits between the markers are overwritten >>>'
END='# <<< herdr-review-panel <<<'

runner="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/review-run.sh"

config_dir="${COLLIE_CONFIG_DIR:-}"
if [ -z "$config_dir" ]; then
  config_dir=$(herdr plugin config-dir herdr.collie 2>/dev/null) || config_dir=""
fi
[ -n "$config_dir" ] || config_dir="$HOME/.config/herdr/plugins/config/herdr.collie"
# Collie not installed on this machine is the normal case, not an error.
[ -d "$config_dir" ] || exit 0
[ -r "$LOG" ] || exit 0

target="$config_dir/launchers.toml"

unescape() {
  local s=$1 out="" i=0 c n
  while [ "$i" -lt "${#s}" ]; do
    c=${s:$i:1}
    if [ "$c" != "\\" ]; then
      out+=$c
      i=$((i + 1))
      continue
    fi
    n=${s:$((i + 1)):1}
    case "$n" in
      n) out+=' ' ;;  # labels are one line; a real newline would break the TOML string
      t) out+=' ' ;;
      r) out+='' ;;
      \\) out+='\' ;;
      "") out+='\' ;;
      *) out+="\\$n" ;;
    esac
    i=$((i + 2))
  done
  printf '%s' "$out"
}

field() {
  local line=$1 key=$2 f
  while IFS= read -r f; do
    case "$f" in
      "$key="*) printf '%s' "${f#"$key"=}"; return 0 ;;
    esac
  done < <(printf '%s\n' "$line" | tr '\t' '\n')
  return 1
}

# TOML basic string: backslash first, then quote.
toml_escape() {
  local s=$1
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '%s' "$s"
}

marks=$(cat "$DONE_LOG" "$CLEARED_LOG" 2>/dev/null)

rows=""
count=0
# Newest last in the log, and the newest items are the ones worth a phone row, so walk backwards.
while IFS= read -r line; do
  [ "$count" -ge "$MAX_ROWS" ] && break
  case "$line" in
    *"	"*) : ;;
    *) continue ;;
  esac
  [ "$(field "$line" kind)" = "command" ] || continue

  ts=${line%%	*}
  raw_item=$(field "$line" item) || continue
  session=$(field "$line" session) || session=""
  key="$ts|$session|$raw_item"
  case "$marks" in
    *"$key"*) continue ;;   # already done or cleared on the desktop
  esac

  id=$(printf '%s\t%s' "$ts" "$raw_item" | sha256sum | cut -c1-8)
  step=$(field "$line" step) || step=""
  cwd=$(unescape "$(field "$line" cwd || printf '%s' "$HOME")")

  label=$(unescape "$raw_item")
  label=${label//  / }
  [ "${#label}" -gt 44 ] && label="${label:0:43}…"
  [ -n "$step" ] && label="$step. $label"

  rows+="[[launchers]]"$'\n'
  rows+="command = \"$(toml_escape "$runner") $id\""$'\n'
  rows+="label = \"$(toml_escape "$label")\""$'\n'
  rows+="cwd = \"$(toml_escape "$cwd")\""$'\n'
  rows+=$'\n'
  count=$((count + 1))
done < <(tac "$LOG")

tmp=$(mktemp "${target}.XXXXXX") || exit 0
trap 'rm -f "$tmp"' EXIT

# Everything outside the managed block is the operator's and is copied through untouched.
if [ -f "$target" ]; then
  awk -v b="$BEGIN" -v e="$END" '
    $0 == b { skip = 1; next }
    $0 == e { skip = 0; next }
    !skip   { print }
  ' "$target" >"$tmp"
fi

if [ "$count" -gt 0 ]; then
  {
    printf '%s\n' "$BEGIN"
    printf '# %d queued command(s). Each row asks before it runs. Regenerated by the Stop hook.\n' "$count"
    printf '%s' "$rows"
    printf '%s\n' "$END"
  } >>"$tmp"
fi

mv -f "$tmp" "$target"
trap - EXIT
